upstream django_backend {
    server backend:8000;
    keepalive 16;
}

server {
    listen 80;
    server_name daengglejeju.site;

    client_max_body_size 20M;
    keepalive_timeout 65;

    # 정적/미디어 파일
    location /static/ {
        alias /static/;
        access_log off;
        expires 1h;
    }
    location /media/ {
        alias /media/;
        access_log off;
        expires 1h;
    }

    # Django 앱
    location / {
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://django_backend;
    }

    server {
    listen 443 ssl http2;
    server_name daengglejeju.site;

    ssl_certificate     /etc/letsencrypt/live/daengglejeju.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/daengglejeju.site/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
