PRESET_BREEDS = [
    ("other", "기타"),
    ("golden-retriever", "골든 리트리버"),
    ("dachshund", "닥스훈트"),
    ("doberman", "도베르만"),
    ("labrador-retriever", "래브라도 리트리버"),
    ("rottweiler", "로트와일러"),
    ("maltese", "말티즈"),
    ("mix", "믹스견"),
    ("basset-hound", "바셋 하운드"),
    ("bernese-mountain-dog", "버니즈 마운틴 독"),
    ("border-collie", "보더 콜리"),
    ("beagle", "비글"),
    ("bichon-frise", "비숑 프리제"),
    ("bulldog", "불독"),
    ("samoyed", "사모예드"),
    ("shetland-sheepdog", "셔틀랜드 쉽독"),
    ("shiba-inu", "시바 이누"),
    ("shih-tzu", "시츄"),
    ("irish-setter", "아이리시 세터"),
    ("akita", "아키타"),
    ("alaskan-malamute", "알래스칸 말라뮤트"),
    ("yorkshire-terrier", "요크셔테리어"),
    ("welsh-corgi", "웰시 코기"),
    ("italian-greyhound", "이탈리안 그레이하운드"),
    ("jack-russell-terrier", "잭 러셀 테리어"),
    ("chihuahua", "치와와"),
    ("cocker-spaniel", "코커 스파니엘"),
    ("poodle", "푸들"),
    ("french-bulldog", "프렌치 불도그"),
    ("siberian-husky", "허스키"),
]
